### ISSUE TITLE
Compiler warnings when compiling c/src/pfio/pfio.c

### ISSUE THREAD

**Issue by proebrock** [thomasmacpherson/piface#13]
Compiling the current C implementation gives:

```
phil@philbox ~/piface/c/src/piface $ make
gcc -Wall -c -o pfio.o pfio.c
pfio.c: In function ‘pfio_init’:
pfio.c:65:5: warning: pointer targets in passing argument 1 of ‘snprintf’ differ in signedness [-Wpointer-sign]
/usr/include/stdio.h:387:12: note: expected ‘char * __restrict__’ but argument is of type ‘uint8_t *’
pfio.c:72:5: warning: pointer targets in passing argument 1 of ‘open’ differ in signedness [-Wpointer-sign]
/usr/include/fcntl.h:119:12: note: expected ‘const char *’ but argument is of type ‘uint8_t *’
```

Possible solution: Changing line 64 from

```
uint8_t path[MAXPATH];
```

into

```
char path[MAXPATH];
```

Or is there a special reason for making the string elements of type uint8_t?

Thank's for your help!

Philipp

**Comment by tompreston** [comment]
uint8_t made more sense: https://github.com/thomasmacpherson/piface/pull/12

I'll put testing this on my todo list. In the meantime, checkout Gordon's WiringPihttp://wiringpi.com/ project.

**Comment by tompreston** [comment]
You were right, there was an error. Should be fixed now. https://github.com/thomasmacpherson/piface/pull/14
