### ISSUE TITLE
Issues with relay reseting

### ISSUE THREAD

**Issue by AaronLaRoca** [thomasmacpherson/piface#16]
I have one of the relays on the piface running a fan.  The script that controls the fan checks a temperature sensor and turns on the fan when the temperature is high.  This script runs every fifteen seconds using cron.  The fan is interrupted (turned off for a brief second) every time the script is run.  I am thinking that the init() is the culprit but am not sure.     I suppose I could have the script run at startup instead of using cron. Can anyone shed any light on this?

**Comment by tompreston** [comment]
Hi, this repository is not longer maintained. You can find all the latest software from [piface.github.io](piface.github.io).

The latest PiFace Digital I/O software can be found at: [github.com/piface/pifacedigitalio](github.com/piface/pifacedigitalio)

Documentation is [here](http://piface.github.io/pifacedigitalio).

Specifically to your problem, what's happening is that each time you init, the board is reinitialised and all outputs are set to 0. With the new software it is possible to start your script without initialising the board. See http://piface.github.io/pifacedigitalio/reference.html#pifacedigitalio.core.PiFaceDigital

Here's an example:

```
>>> import pifacedigitalio
>>> # create a PiFace Digtal object without initialising it
>>> pfd = pifacedigitalio.PiFaceDigital(init_board=False)
>>> pfd.relays[0].turn_on()  # turn on the first relay
```

**Comment by AaronLaRoca** [comment]
Thanks.  Worked like a charm. Keep up the good work.
