### ISSUE TITLE
Error while loading shared libraries

### ISSUE THREAD

**Issue by ghost** [thomasmacpherson/piface#9]
I've just setup my PiFace and it works on Python. I'm trying to get it to work on C too however once I follow your instructions I get an error:

```
./piface_program: error while loading shared libraries: libpiface-1.0.so.0: cannot open shared object file: No such file or directory
```

Any ideas why?

**Comment by tompreston** [comment]
I think it could be a file name issue but I'm not sure, I haven't looked at the C library in quite a while (especially since [we have moved](https://github.com/piface)). I'll have a look myself next week. In the mean time, double check where the files have been installed by checking /usr/lib/ etc.

Also, [Gordon Henderson has wrote a nice C library for PiFace](https://projects.drogon.net/raspberry-pi/wiringpiface/).

**Comment by ghost** [comment]
https://projects.drogon.net/raspberry-pi/wiringpiface/

https://projects.drogon.net/raspberry-pi/wiringpi/download-and-install/

On 26 April 2013 12:01, Thomas Preston notifications@github.com wrote:

> I think it could be a file name issue but I'm not sure, I haven't looked
> at the C library in quite a while (especially since we have movedhttps://github.com/piface).
> I'll have a look myself next week. In the mean time, double check where the
> files have been installed by checking /usr/lib/ etc.
> 
> Also, Gordon Henderson has wrote a nice C library for PiFacehttps://projects.drogon.net/raspberry-pi/wiringpiface/
> .
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/thomasmacpherson/piface/issues/9#issuecomment-17067114
> .

## 

_RAFAL CHMIEL_

**Comment by waynix** [comment]
I had to run 
sudo ldconfig
to tell my system to update the lib folder information after installing the current version.

**Comment by ghost** [comment]
Thanks, that worked great. It should be included in the README.

**Comment by Slightly-Mad-Mike** [comment]
Waynix: Fantastic. As a complete Noob I was struggling. Yes, should be in the README.

**Comment by tompreston** [comment]
Hi @Slightly-Mad-Mike, this repository is out of date and due to be deleted. For everything PiFace, head to http://piface.github.io/.
